### ISSUE TITLE
Doesn't work with Forge 1.13

### ISSUE THREAD

**Issue by SiliconExarch** [ThisTestUser/FarLandsMod#1]
Forge 1.13 introduced a new Javascript based system for CoreMods so this mod no longer works.

**Comment by ThisTestUser** [comment]
Unfortunately I will probably not be updating this mod to 1.13, so you'll have to find alternatives.

**Comment by ThisTestUser** [comment]
The far lands mod has been updated to newer versions, but unfortunately not for 1.13 as the coremod transformers work differently  from the 1.14+ versions.
