### ISSUE TITLE
Update to Latest Version

### ISSUE THREAD

**Issue by StereoMadnessss** [ThisTestUser/FarLandsMod#11]
This mod hasn't been updated since 2020 and this is becoming severely outdated by today. The mod at the latest version is supported for 1.16.5 which is disappointing. Other far lands mods like the one by geniii never were continued and that mod hasn't been updated to make it's release for 1.16 which in that case most likely means that the mod has been abandoned. Someone has decided to continue the mod and update it for 1.17.1 but that should be merged with this. 
Updated Mod: 
https://www.curseforge.com/minecraft/mc-mods/farlands-mod/files

**Comment by ThisTestUser** [comment]
This mod is only for 1.12.2 and below, FarLandsModV2 (https://github.com/ThisTestUser/FarLandsModV2) is the mod for 1.14 and above (1.18 will be added soon).
