### ISSUE TITLE
Far Lands on TFC Appear at 8589932

### ISSUE THREAD

**Issue by StereoMadnessss** [ThisTestUser/FarLandsMod#12]
For some reason on TFC the Far Lands appear at 8589932
![2022-04-24_18 00 10](https://user-images.githubusercontent.com/77188051/165004819-a4dbbf08-66c5-43e8-b43f-2f7ea0bc08b3.png)
.

**Comment by ThisTestUser** [comment]
Not an issue, the far lands do not necessarily begin at the same coordinates in custom dimensions.
