### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Spongebobfan907** [ThisTestUser/FarLandsMod#2]
Can you make a config with an option that disables the far lands and just have the 
30,000,000 limit removed

**Comment by ThisTestUser** [comment]
[farlands-1.13NoFarLands.zip](https://github.com/ThisTestUser/FarLandsMod/files/3170472/farlands-1.13NoFarLands.zip)
The Jar i gave you should have no far lands.

**Comment by Spongebobfan907** [comment]
does it works in 1.12 because I play in that version

**Comment by Spongebobfan907** [comment]
oh nevermind it works

**Comment by ThisTestUser** [comment]
The mod doesn't work for 1.13 and above. It was actually supposed to say 1.3 instead of 1.13.
