### ISSUE TITLE
Update to 1.16.1

### ISSUE THREAD

**Issue by muzikbike** [ThisTestUser/FarLandsMod#4]
there's a few dimension mods out for 1.15 that I'm interested in seeing far lands for

**Comment by ThisTestUser** [comment]
Do the other far land mods not work?

**Comment by muzikbike** [comment]
There is the other far lands mod for 1.15, but it's fabric only, and I'm not aware of any forge mods for 1.15 that bring back the far lands

**Comment by ThisTestUser** [comment]
https://github.com/ThisTestUser/FarLandsModV2
